name = "SpatialCvM"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["SpatialCvM"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc1"

[[lean_lib]]
name = "SpatialCvM"

[[lean_exe]]
name = "spatialcvm"
srcDir = "."
root = "Main"
