import Mathlib
import Mathlib.Analysis.BoxIntegral.Basic
import Mathlib.MeasureTheory.Integral.SetIntegral
import Mathlib.Topology.Instances.Real
import Mathlib.Topology.MetricSpace.Basic

open MeasureTheory Topology Filter Real BigOperators

/-! # Riemann Sum Convergence Utilities

This module provides the theoretical foundation for approximating integrals
via Riemann sums on spatial lattices. This is essential for proving that
discrete spatial sums converge to continuous integrals as the lattice
mesh size → 0.

## Mathematical Context

In spatial statistics and kernel smoothing, we often need to show:

    ∑_{j ∈ lattice} f(j) · Δ² → ∫_{ℝ²} f(x) dx

as the mesh size Δ → 0. This is the Riemann sum convergence theorem
extended to ℝ².

## Key Theorems

1. **riemannSum_converges**: For continuous compactly supported f,
   the Riemann sum converges to the integral.

2. **doubleRiemannSum_converges**: For double sums (product measures),
   convergence to the iterated integral.

3. **scaled_riemannSum_converges**: For scaled kernels K((j-s₀)/h).

## Sources

- **Courant**: Differential and Integral Calculus (classic Riemann sums)
- **Rudin**: Principles of Mathematical Analysis, Chapter 6
- **Measure Theory**: Folland, Chapter 2 (Lebesgue vs Riemann)
- **Spatial Discretization**: Doukhan et al. (2002), numerical analysis

## Axioms and Assumptions

1. **Continuity**: Functions must be continuous (or at least Riemann integrable)
2. **Compact Support**: Ensures integrability and finite sums
3. **Mesh → 0**: The lattice becomes dense in the limit
4. **Bounded Domain**: (Implicit via compact support)

Author: SpatialCvM Project
Date: 2026-04-23
-/

namespace RiemannSum

/-! ## Setup: ℝ² as a Normed Space -/

-- We work in ℝ² with product measure
abbrev Loc := ℝ × ℝ

/-- ℝ² is a normed additive commutative group

The norm is the standard Euclidean norm: ‖(x,y)‖ = √(x² + y²)

**Axioms** (from Mathlib NormedAddCommGroup):
- ‖x‖ ≥ 0 with equality iff x = 0
- ‖x + y‖ ≤ ‖x‖ + ‖y‖ (triangle inequality)
- ‖-x‖ = ‖x‖ (symmetry)
- Compatible with addition and scalar multiplication

**Source**: Mathlib Analysis.NormedSpace.Basic
-/
instance : NormedAddCommGroup Loc := by
  unfold Loc
  infer_instance

/-- ℝ² is a real vector space

Scalar multiplication: α · (x, y) = (αx, αy)

**Axioms** (Module structure):
- 1 · v = v (identity)
- α · (β · v) = (αβ) · v (compatibility)
- α · (u + v) = α · u + α · v (distributivity)
- (α + β) · v = α · v + β · v (distributivity)

**Source**: Mathlib Algebra.Module.Basic
-/
noncomputable instance : Module ℝ Loc := by
  unfold Loc
  infer_instance

/-- ℝ² has the Borel σ-algebra

The Borel σ-algebra is generated by open sets.
Measurable sets include intervals, balls, and countable unions thereof.

**Key Property**: Borel σ-algebra makes continuous functions measurable.

**Source**: Mathlib MeasureTheory.MeasurableSpace.Basic
-/
instance : MeasurableSpace Loc := by
  unfold Loc
  infer_instance

/-- ℝ² has the Lebesgue measure

The Lebesgue measure is the completion of the product measure
on ℝ × ℝ. It assigns to rectangles their area.

**Properties**:
- Translation invariant: λ(A + x) = λ(A)
- σ-finite: ℝ² = ∪_n B(0, n)
- Complete: subsets of null sets are measurable
- Regular: approximation by open/compact sets

**Axioms** (Measure space):
- λ(∅) = 0
- Countable additivity for disjoint sets

**Source**: Measure theory standard (Folland, Chapter 1)
-/
instance : MeasureSpace Loc := by
  unfold Loc
  infer_instance

/-! ## Lattice Structure -/

/-- A lattice for Riemann sums

A lattice represents a discrete approximation of ℝ² using finitely many points.
Each point j in the lattice corresponds to a cell of area mesh² centered at j.

**Components**:
- `points`: Finite set of sampling locations (Finset Loc)
- `mesh`: Maximum distance between adjacent lattice points
- `mesh_pos`: Mesh size is strictly positive
- `covers`: Covering property - every point in space is near some lattice point

**Physical Interpretation**:
In spatial statistics, this represents sampling locations at which we observe
the random field. The "mesh" is the maximum sampling interval.

**Examples**:
1. Regular grid: points = {(i/n, j/n) : i,j ∈ {0,...,n-1}}
2. Hexagonal lattice: optimal packing in ℝ²
3. Irregular lattice: adaptive sampling

**Mathematical Property** (from `covers`):
The lattice is "dense enough" that every point in ℝ² is within distance
`mesh` of some lattice point. This ensures the Riemann sum captures
the behavior of the function everywhere.

**Source**: Numerical analysis, finite element methods
-/
structure Lattice where
  /-- Finite set of lattice points (sampling locations) -/
  points : Finset Loc
  /-- Mesh size (maximum spacing between points) -/
  mesh : ℝ
  /-- Positivity: mesh must be strictly positive -/
  mesh_pos : 0 < mesh
  /-- Covering property: every location is near some lattice point -/
  -- Each point represents a cell of size mesh²
  covers : ∀ x : Loc, ∃ j ∈ points, ‖j - x‖ ≤ mesh

/-! ## Riemann Sum Definitions -/

/-- Standard Riemann sum

**Formula**: R(f, L) = ∑_{j ∈ L.points} f(j) · mesh²

**Interpretation**:
- Sample f at lattice points j
- Multiply by cell area mesh²
- Sum over all cells

**Riemann Integral Intuition**:
As mesh → 0, the Riemann sum approximates:
  ∫_{ℝ²} f(x) dx ≈ ∑ f(j) · (area of cell around j)

**Why mesh²?**:
In ℝ², mesh is a length, so mesh² is an area. The Riemann sum weights
samples by the area they represent.

**Condition for Convergence**:
f must be continuous (or at least Riemann integrable) and compactly supported.

**Source**: Standard Riemann integration theory (Courant, Rudin)
-/
def riemannSum (L : Lattice) (f : Loc → ℝ) : ℝ :=
  ∑ j ∈ L.points, f j * (L.mesh)^2

/-- Scaled Riemann sum for kernel applications

**Formula**: R(f, L, s₀, h) = ∑_j f((j - s₀)/h) · mesh²

**Motivation**:
In kernel smoothing, we evaluate the kernel at shifted/scaled locations:
  K_h(j - s₀) = (1/h²) K((j - s₀)/h)

This definition isolates the function evaluation part, leaving scaling to the caller.

**Change of Variables Insight**:
If u = (j - s₀)/h, then mesh² corresponds to du · h² in the continuous limit:
  ∑ f((j-s₀)/h) mesh² → h² ∫ f(u) du

**Application**:
Used in the denominator asymptotic lemma where we show:
  [∑ K((j-s₀)/h) mesh²] → h² ∫ K(u) du = h²

**Source**: Kernel smoothing theory (Silverman 1986, Ch. 3)
-/
def riemannSumScaled (L : Lattice) (f : Loc → ℝ) (s₀ : Loc) (h : ℝ) : ℝ :=
  ∑ j ∈ L.points, f ((j.1 - s₀.1) / h, (j.2 - s₀.2) / h) * (L.mesh)^2

/-! ## Convergence Theorems -/

/-- **Theorem**: Riemann sum converges to the integral

**Statement**:
For continuous compactly supported f:

    lim_{mesh → 0} ∑ f(j) · mesh² = ∫ f(x) dx

**Proof Strategy**:
1. Show f is Lebesgue integrable (continuous + compact support)
2. Use standard Riemann sum convergence (tendsto_integral_sum_of_mesh_zero)
3. Verify mesh → 0 (using hL: mesh = 1/(n+1) → 0)

**Conditions** (Axioms/Assumptions):
- `hf_cont`: f is continuous (ensures Riemann integrability)
- `hf_supp`: f has compact support (ensures integrability)
- `hL`: Mesh size goes to 0 as n → ∞

**Why These Conditions?**
- Continuity: Prevents pathological cases like Dirichlet function
- Compact support: Ensures finite integral over unbounded ℝ²
- Mesh → 0: Standard requirement for Riemann sum convergence

**Mathematical Source**:
- Riemann-Lebesgue theory: Continuous compactly supported functions are dense in L¹
- Box integration: Mathlib's tendsto_integral_sum_of_mesh_zero
- Standard textbooks: Rudin Ch. 6, Folland Ch. 2

**History**:
- Riemann (1854): Original definition for bounded intervals
- Lebesgue (1902): Generalization via measure theory
- Modern: Convergence holds for Riemann integrable functions (a.e. continuous, bounded)
-/
theorem riemannSum_converges {f : Loc → ℝ}
    (hf_cont : Continuous f) (hf_supp : ∃ r > 0, ∀ x, ‖x‖ > r → f x = 0)
    (L : ℕ → Lattice) (hL : ∀ n, (L n).mesh = 1 / (n + 1)) :
    Tendsto (fun n => riemannSum (L n) f) atTop (𝓝 (∫ x : Loc, f x)) := by

  -- First, establish that f is integrable
  have hf_int : Integrable f := by
    apply Integrable.of_continuous_of_support
    · exact hf_cont
    · -- Compact support implies integrable
      rcases hf_supp with ⟨r, hr_pos, hr_supp⟩
      apply HasCompactSupport.of_support_subset_isCompact
      · apply isCompact_closedBall (0 : Loc) r
      · -- Show support is contained in closed ball
        intro x hx
        by_contra h
        push_neg at h
        have : f x = 0 := hr_supp x h
        contradiction

  -- Use box integral convergence (standard result)
  -- For continuous compactly supported functions, Riemann sums converge
  apply tendsto_integral_sum_of_mesh_zero
  · exact hf_cont
  · exact hf_int
  · -- Mesh goes to zero by our hypothesis
    rw [tendsto_iff_dist_tendsto_zero]
    simp [dist_eq_norm, hL]
    apply tendsto_one_div_nat_add_one

/-- **Theorem**: Double Riemann sum converges to double integral

**Statement**:
For continuous f with compact support:

    lim_{mesh→0} ∑_j ∑_ℓ f(j,ℓ) · mesh⁴ = ∬ f(x,y) dx dy

**Explanation**:
- mesh⁴ = (mesh²)² represents the area of 2D cell in product space
- The double sum approximates the integral over ℝ² × ℝ²

**Connection to Main Proof**:
In Lemma1, we need:
  ∑_j ∑_ℓ K((j-s₀)/h) K((ℓ-s₀)/h) γ(j-ℓ) mesh⁴

This becomes:
  ∬ K(u)K(v) γ(h(u-v)) du dv · h⁴

**Proof Strategy**:
1. Apply Fubini's theorem: ∬ f(x,y) dx dy = ∫(∫ f(x,y) dy) dx
2. Use single Riemann sum convergence twice
3. Uniform convergence justifies interchange

**Axioms**:
- Fubini's theorem (for equality of iterated integrals)
- Continuity of f (ensures measurability)
- Compact support (ensures integrability)

**Source**: Folland, Real Analysis, Chapter 2 (Product measures and Fubini)
-/
theorem doubleRiemannSum_converges {f : Loc → Loc → ℝ}
    (hf : Continuous (fun p : Loc × Loc => f p.1 p.2))
    (hf_supp : ∃ r > 0, ∀ x y, ‖x‖ > r ∨ ‖y‖ > r → f x y = 0)
    (L : ℕ → Lattice) (hL : ∀ n, (L n).mesh = 1 / (n + 1)) :
    Tendsto (fun n => ∑ j ∈ (L n).points, ∑ ℓ ∈ (L n).points,
      f j ℓ * ((L n).mesh)^4) atTop (𝓝 (∬ x : Loc, f x x)) := by

  -- Use Fubini/Tonelli combined with single Riemann sum convergence
  have h1 : ∫ x : Loc, f x x = ∫ x₂ : ℝ, ∫ x₁ : ℝ, f (x₁, x₂) (x₁, x₂) := by
    simp [show Loc = ℝ × ℝ from rfl, MeasureTheory.integral_prod]

  rw [h1]
  sorry -- Requires careful setup of iterated integrals

/-- **Theorem**: Scaled function Riemann sum convergence

**Statement**:
For scaled kernel evaluation f((j-s₀)/h):

    ∑ f((j-s₀)/h) · mesh² → h² ∫ f(u) du

**Derivation**:

Step 1: Change of variables
Let u = (j - s₀)/h, then:
- When j ranges over lattice with spacing mesh
- u ranges over lattice with spacing mesh/h

Step 2: Riemann sum in u-space
  ∑_j f(u_j) · (mesh/h)² → ∫ f(u) du

Step 3: Convert back
  ∑_j f((j-s₀)/h) · mesh² = h² · ∑_j f(u_j) · (mesh/h)²
                           → h² · ∫ f(u) du

**Application in Lemma1**:
For the denominator normalization:
  ∑ K_h(j-s₀) · mesh² = (1/h²) ∑ K((j-s₀)/h) · mesh² → 1

**Verification**: h² · (1/h²) · ∫ K = ∫ K = 1 ✓

**Conditions**:
- Same as riemannSum_converges (continuity, compact support)
- Additional: h > 0 (positive bandwidth)

**Source**: Change of variables in Lebesgue integrals (Folland Ch. 2)
-/
theorem scaled_riemannSum_converges {f : Loc → ℝ}
    (hf_cont : Continuous f) (hf_supp : ∃ r > 0, ∀ x, ‖x‖ > r → f x = 0)
    (L : ℕ → Lattice) (hL : ∀ n, (L n).mesh = 1 / (n + 1))
    (s₀ : Loc) (h : ℝ) (_h_pos : 0 < h) :
    Tendsto (fun n => riemannSumScaled (L n) f s₀ h) atTop
      (𝓝 (h^2 * ∫ u : Loc, f u)) := by

  -- Change of variables: u = (j - s₀)/h, du = dj/h²
  -- So sum over j becomes h² ∫ f(u) du
  unfold riemannSumScaled
  have h1 : ∀ n, ∑ j ∈ (L n).points, f ((j.1 - s₀.1) / h, (j.2 - s₀.2) / h) * ((L n).mesh)^2 =
      h^2 * ∑ j ∈ (L n).points, f ((j.1 - s₀.1) / h, (j.2 - s₀.2) / h) * ((L n).mesh / h)^2 := by
    intro n
    field_simp
    ring_nf
    sorry

  rw [funext h1]

  -- Now the inner sum is a Riemann sum for the scaled lattice with mesh' = mesh/h
  sorry -- Apply riemannSum_converges with appropriate scaling

end RiemannSum
