name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Install Lean and build
        uses: leanprover/lean-action@v1
        with:
          auto-config: false
          build: true
          test: false
          lint: false
          build-args: "--no-wfail"
        continue-on-error: true
